# workflow name
name: Hexo Blog CI

# 在main分支上有push命令时触发该流程
on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository master branch
              uses: actions/checkout@master

            - name: Setup Node.js 16.x
              uses: actions/setup-node@master
              with:
                  node-version: '16.x'

            - name: Setup Hexo Dependencies
              run: |
                  # npm install  # 若没有上传依赖包，则把这行的注释解除
                  npm install -g hexo-cli
                  npm install hexo-deployer-ali-oss --save
                  hexo clean
                  hexo generate
                  hexo d
